# Generated by Django 5.1.1 on 2025-12-02 03:11

import django.core.validators
import django.db.models.deletion
import lego_inventory.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the campaign', max_length=100)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=lego_inventory.models.Character.user_directory_path)),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(help_text="Character's race, e.g., Elf, Human, Dwarf", max_length=50)),
                ('background', models.CharField(help_text="Character's background, e.g., Soldier, Noble", max_length=50)),
                ('charClass', models.CharField(help_text="Character's class, e.g., Fighter, Wizard, Rogue", max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-Binary'), ('O', 'Other')], help_text='Gender identity of the character', max_length=2)),
                ('strength', models.IntegerField(help_text='Strength (1-30)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('dexterity', models.IntegerField(help_text='Dexterity (1-30)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('constitution', models.IntegerField(help_text='Constitution (1-30)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('intelligence', models.IntegerField(help_text='Intelligence (1-30)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('wisdom', models.IntegerField(help_text='Wisdom (1-30)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('charisma', models.IntegerField(help_text='Charisma (1-30)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('hitPoints', models.IntegerField(help_text='Current hit points', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('maxHitPoints', models.IntegerField(help_text='Maximum hit points', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('armorClass', models.IntegerField(help_text='Armor Class (AC)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('speed', models.IntegerField(help_text='Movement speed in feet per round', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('proficiencyBonus', models.IntegerField(help_text='Proficiency bonus (1-6)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('level', models.IntegerField(help_text='Character level (1-20)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('experiencePoints', models.IntegerField(default=0, help_text='Experience points accumulated', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('athletics', models.BooleanField(default=False, help_text='Proficient in Athletics (Strength-based)')),
                ('acrobatics', models.BooleanField(default=False, help_text='Proficient in Acrobatics (Dexterity-based)')),
                ('sleightOfHand', models.BooleanField(default=False, help_text='Proficient in Sleight of Hand (Dexterity-based)')),
                ('stealth', models.BooleanField(default=False, help_text='Proficient in Stealth (Dexterity-based)')),
                ('arcana', models.BooleanField(default=False, help_text='Proficient in Arcana (Intelligence-based)')),
                ('history', models.BooleanField(default=False, help_text='Proficient in History (Intelligence-based)')),
                ('investigation', models.BooleanField(default=False, help_text='Proficient in Investigation (Intelligence-based)')),
                ('nature', models.BooleanField(default=False, help_text='Proficient in Nature (Intelligence-based)')),
                ('religion', models.BooleanField(default=False, help_text='Proficient in Religion (Intelligence-based)')),
                ('animalHandling', models.BooleanField(default=False, help_text='Proficient in Animal Handling (Wisdom-based)')),
                ('insight', models.BooleanField(default=False, help_text='Proficient in Insight (Wisdom-based)')),
                ('medicine', models.BooleanField(default=False, help_text='Proficient in Medicine (Wisdom-based)')),
                ('perception', models.BooleanField(default=False, help_text='Proficient in Perception (Wisdom-based)')),
                ('survival', models.BooleanField(default=False, help_text='Proficient in Survival (Wisdom-based)')),
                ('deception', models.BooleanField(default=False, help_text='Proficient in Deception (Charisma-based)')),
                ('intimidation', models.BooleanField(default=False, help_text='Proficient in Intimidation (Charisma-based)')),
                ('performance', models.BooleanField(default=False, help_text='Proficient in Performance (Charisma-based)')),
                ('persuasion', models.BooleanField(default=False, help_text='Proficient in Persuasion (Charisma-based)')),
                ('campaigns', models.ManyToManyField(blank=True, related_name='campaign_characters', to='dndCharacterCustomizer.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='characters',
            field=models.ManyToManyField(blank=True, help_text='Characters participating in this campaign', related_name='character_campaigns', to='dndCharacterCustomizer.character'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ADMIN', 'Admin'), ('AUTHORIZED', 'Authorized')], default='AUTHORIZED', max_length=10)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('reset_token', models.CharField(blank=True, max_length=64, null=True)),
                ('campaigns', models.ManyToManyField(blank=True, related_name='profile_campaigns', to='dndCharacterCustomizer.campaign')),
                ('characters', models.ManyToManyField(blank=True, to='dndCharacterCustomizer.character')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='owners', to='dndCharacterCustomizer.profile'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='campaign_profiles', to='dndCharacterCustomizer.profile'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='userOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dndCharacterCustomizer.profile'),
        ),
    ]
